name: ChromeBotWin

on:
  workflow_dispatch:

jobs:
  mouse-action:
    runs-on: windows-latest
    steps:
      - name: click.ps1 scriptini indir
        run: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/Orduo/selam/main/click.ps1" -OutFile "click.ps1"

      - name: Mouse hareketleri + yazı + ekran görüntüsü
        run: powershell -ExecutionPolicy Bypass -File click.ps1

      - name: İlk screenshot'ı artefact olarak yükle
        uses: actions/upload-artifact@v4
        with:
          name: screenshot1
          path: screenshot1.png

      - name: İkinci screenshot'ı artefact olarak yükle
        uses: actions/upload-artifact@v4
        with:
          name: screenshot2
          path: screenshot2.png
