name: Screenshot Al

on:
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: windows-latest
    steps:
      - name: PowerShell screenshot scriptini indir
        run: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/Orduo/selam/main/ss.ps1" -OutFile "ss.ps1"

      - name: Screenshot al
        run: powershell -ExecutionPolicy Bypass -File ss.ps1

      - name: Artifact olarak yükle
        uses: actions/upload-artifact@v4
        with:
          name: ekran-goruntusu
          path: screenshot.png
