name: ChromeBotWin

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
    - cron: '12 1 * * *'
    - cron: '24 2 * * *'
    - cron: '36 3 * * *'
    - cron: '48 4 * * *'
    - cron: '0 6 * * *'
    - cron: '12 7 * * *'
    - cron: '24 8 * * *'
    - cron: '36 9 * * *'
    - cron: '48 10 * * *'
    - cron: '0 12 * * *'
    - cron: '12 13 * * *'
    - cron: '24 14 * * *'
    - cron: '36 15 * * *'
    - cron: '48 16 * * *'
    - cron: '0 18 * * *'
    - cron: '12 19 * * *'
    - cron: '24 20 * * *'
    - cron: '36 21 * * *'
    - cron: '48 22 * * *'

jobs:
  mouse-action:
    runs-on: windows-latest
    steps:
      - name: click.ps1 scriptini indir
        run: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/Orduo/selam/main/click.ps1" -OutFile "click.ps1"

      - name: Mouse hareketleri + yazı + ekran görüntüsü
        run: powershell -ExecutionPolicy Bypass -File click.ps1

      - name: İlk screenshot'ı artefact olarak yükle
        uses: actions/upload-artifact@v4
        with:
          name: screenshot1
          path: screenshot1.png

      - name: İkinci screenshot'ı artefact olarak yükle
        uses: actions/upload-artifact@v4
        with:
          name: screenshot2
          path: screenshot2.png

      - name: İlk screenshot'ı artefact olarak yükle
        uses: actions/upload-artifact@v4
        with:
          name: screenshot3
          path: screenshot3.png

      - name: İkinci screenshot'ı artefact olarak yükle
        uses: actions/upload-artifact@v4
        with:
          name: screenshot4
          path: screenshot4.png
